From: Tester <test@localhost>
Content-Type: multipart/alternative;
	boundary="Apple-Mail=_872043AF-1DA2-4CAB-A04C-CC61CAD82D58"
X-Smtp-Server: localhost:thomas
Subject: XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X
Message-Id: <D52369C5-FBC1-46E9-A07E-57F6E00097E6@localhost>
X-Universally-Unique-Identifier: 7B72F302-DA73-41D9-A34D-F03F3CC8DE17
Date: Tue, 31 Mar 2015 15:37:27 +0200
To: test@localhost
Mime-Version: 1.0 (Mac OS X Mail 8.2 \(2070.6\))


--Apple-Mail=_872043AF-1DA2-4CAB-A04C-CC61CAD82D58
Content-Transfer-Encoding: 7bit
Content-Type: text/plain;
	charset=us-ascii

XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X


--Apple-Mail=_872043AF-1DA2-4CAB-A04C-CC61CAD82D58
Content-Transfer-Encoding: 7bit
Content-Type: text/html;
	charset=us-ascii

<html><head><meta http-equiv="Content-Type" content="text/html charset=us-ascii"><meta http-equiv="Content-Type" content="text/html charset=us-ascii"><meta http-equiv="Content-Type" content="text/html charset=us-ascii"></head><body style="word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;" class=""><pre style="background-color: rgb(255, 255, 255);" class="">XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X</pre><div class=""><br class=""></div></body></html>
--Apple-Mail=_872043AF-1DA2-4CAB-A04C-CC61CAD82D58--
